table Product
	lineageTag: 4ce97987-a588-4b3b-b61c-6230b41331a6

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: c0d36ef4-0f4b-4129-9913-6f1198148783
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 00382b5c-9624-48b7-8b23-72da36c3d307
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 7af77ffe-a8a5-4136-9238-087ee4301cd9
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 5d89dfcf-35da-44d2-a1c9-7a76634d57df
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Product = m
		mode: import
		source =
				let
				    Source = Sql.Databases("LACHI\SQL2022"),
				    db_revision_generale = Source{[Name="db_revision_generale"]}[Data],
				    ods_dim_product = db_revision_generale{[Schema="ods",Item="dim_product"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(ods_dim_product,{"ods.fact_sales"})
				in
				    #"Colonnes supprimées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

